### ISSUE TITLE
開発元がUnknowになる例

### ISSUE THREAD

**Issue by ryhanai** [n-ando/macapplister#5]
開発元番号が無い例

    Adobe Application Manager:

      Version: 10.0.0.49
      Obtained from: Identified Developer
      Last Modified: 2020/12/11 15:39
      Kind: 32-bit (Unsupported)
      Signed by: Developer ID Application: Adobe Systems, Inc., Developer ID Certification Authority, Apple Root CA
      Location: /Applications/Utilities/Adobe Application Manager/core/Adobe Application Manager.app
      Get Info String: Adobe Application Manager 10.0.0.49, Copyright 2009-2015 Adobe Systems Incorporated. All rights reserved.

App Storeの例    Slack:

      Version: 4.14.1
      Obtained from: App Store
      Last Modified: 2021/04/05 17:58
      Kind: Universal
      Signed by: Apple Mac OS Application Signing, Apple Worldwide Developer Relations Certification Authority, Apple Root CA
      Location: /Applications/Slack.app

**Comment by n-ando** [comment]
一応、上記の問題は解決したと思いますので試してみてください。
ちなみに、OSのバージョンはBig Surでしょうか？

**Comment by ryhanai** [comment]
Big Surです。
正規表現にうまくマッチしないものがあるので、以下の変更をすると問題がありますでしょうか？

```
diff --git a/macapplister b/macapplister
index 16f2baa..1ca465a 100755
--- a/macapplister
+++ b/macapplister
@@ -113,7 +113,7 @@ def parse_results(proc):
                     continue
                 # Signed vendors' app without ID number
                 m0 = re.match(
-                    r'\s*Developer ID Application: (\S+), Developer ID.*$',
+                    r'\s*Developer ID Application: (.+), Developer ID.*$',
                     tag_value)
                 if m0:
                     appinfo['Vendor'] = m0.group(1).strip()
```

**Comment by n-ando** [comment]
ありがとうございます。修正しました。
ID Application: の次に空白が2つ以上あったのでしょうか？

**Comment by ryhanai** [comment]
以下のように括弧がないパターンで、Vendor名に空白があるとmatchしませんでした。
Developer ID Application: Adobe Systems, Inc., Developer ID Certification Authority, Apple Root CA

手元で確認して問題なさそうなのでクローズします。
